-- SELECT * FROM customer LIMIT 10
--Q1. What is the total revenue generated by male vs. female customers?

-- SELECT gender, 
-- SUM(purchase_amount) as revenue
-- FROM customer
-- GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
-- SELECT customer_id, purchase_amount
-- FROM customer
-- WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
-- LIMIT 10

--Q3. Which are the top 5 products with the highest average review rating?
-- SELECT item_purchased, ROUND(AVG (review_rating:: numeric), 2) as "Average Product Rating"
-- FROM customer
-- group by item_purchased
-- order by avg(review_rating) desc
-- limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- SELECT shipping_type,
-- ROUND(AVG(purchase_amount),2)
-- FROM customer
-- WHERE shipping_type in ('Standard', 'Express')
-- GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between

-- SELECT subscription_status,
-- COUNT(customer_id) as total_customers,
-- ROUND(AVG(purchase_amount),2) AS avg_spend,
-- ROUND(SUM(purchase_amount),2) AS total_revenue
-- FROM customer
-- GROUP BY subscription_status
-- ORDER BY total_revenue DESC, avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- SELECT item_purchased,
-- ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
-- FROM customer
-- GROUP BY item_purchased
-- ORDER BY discount_rate DESC
-- LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

-- with customer_type as (
-- select customer_id, previous_purchases,
-- CASE
-- 	WHEN previous_purchases = 1 THEN 'New'
-- 	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
-- 	ELSE 'Loyal'
-- 	END AS customer_segment
-- 	from customer
-- )
-- select customer_segment, count(*) as "Number of Customers"
-- from customer_type
-- group by customer_segment

--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category 
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count (customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;